defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run: npx npm@5.7.1 ci

      - run: npm test
      
      - run: npm run build
            
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
            - now.json

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      
      - run: npx now --token ${NOW_TOKEN} --name trendlock dist/
      
  promote:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
                
      - run: 
         name: alias deployment
         command: npx now --token ${NOW_TOKEN} alias
                
      - run: 
         name: cleanup
         command: npx now --token ${NOW_TOKEN} rm --safe --yes trendlock

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - promote:
          requires:
            - deploy
          filters:
            branches:
              only: master