defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm test
      
      - run: npm run build
            
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
            - now.json

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      
      - run: npx now --token ${NOW_TOKEN} --name trendlock dist/
      
  promote:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
                
      - run: npx now --token ${NOW_TOKEN} alias

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - promote:
          requires:
            - deploy
          filters:
            branches:
              only: master